print('------DESAFIO 04--------')
algo = input('Digite algo: ')
print('Qual tipo da sua variavel?',(type(algo)))
print('O que ela está imprimindo?',algo.isalnum())
print('O que ela está imprimindo?',algo.isalpha())
print('O que ela está imprimindo?',algo.isdecimal())
print('O que ela está imprimindo?',algo.isdigit())
print('O que ela está imprimindo?',algo.isidentifier())
print('O que ela está imprimindo?',algo.islower())
print('O que ela está imprimindo?',algo.isnumeric())
print('O que ela está imprimindo?',algo.isprintable())
print('O que ela está imprimindo?',algo.isspace())
print('O que ela está imprimindo?',algo.istitle())
print('O que ela está imprimindo?',algo.isupper())